export const routes = [
  {
    name: "about",
    path: "/about",
    controller: "AboutController",
    templateUrl: "app/pages/about/about.view.html",
    resolve: ["app/pages/about/about.style.css"],
  },
  {
    name: "aboutMe",
    path: "/about-me",
    controller: "AboutMeController",
    templateUrl: "app/pages/aboutMe/aboutMe.view.html",
    resolve: ["app/pages/aboutMe/aboutMe.style.css"],
  },
  {
    name: "calendar",
    path: "/calendar",
    controller: "CalendarController",
    templateUrl: "app/pages/calendar/calendar.view.html",
    resolve: ["app/pages/calendar/calendar.style.css"],
  },
  {
    name: "company",
    path: "/company",
    controller: "CompanyController",
    templateUrl: "app/pages/company/company.view.html",
    resolve: ["app/pages/company/company.style.css"],
  },
  {
    name: "contact",
    path: "/contact",
    controller: "ContactController",
    templateUrl: "app/pages/contact/contact.view.html",
    resolve: ["app/pages/contact/contact.style.css"],
  },
  {
    name: "dashboard",
    path: "/",
    controller: "DashboardController",
    templateUrl: "app/pages/dashboard/dashboard.view.html",
    resolve: ["app/pages/dashboard/dashboard.style.css"],
  },
  {
    name: "explore",
    path: "/explore",
    controller: "ExploreController",
    templateUrl: "app/pages/explore/explore.view.html",
    resolve: ["app/pages/explore/explore.style.css"],
  },
  {
    name: "login",
    path: "/login",
    controller: "LoginController",
    templateUrl: "app/pages/login/login.view.html",
    resolve: ["app/pages/login/login.style.css"],
  },
  {
    name: "messages",
    path: "/messages",
    controller: "MessageController",
    templateUrl: "app/pages/message/message.view.html",
    resolve: ["app/pages/message/message.style.css"],
  },
  {
    name: "posts",
    path: "/posts",
    controller: "PostsController",
    templateUrl: "app/pages/posts/posts.view.html",
    resolve: ["app/pages/posts/posts.style.css"],
  },
  {
    name: "profile",
    path: "/profile",
    controller: "ProfileController",
    templateUrl: "app/pages/profile/profile.view.html",
    resolve: ["app/pages/profile/profile.style.css"],
  },
  {
    name: "projects",
    path: "/projects",
    controller: "ProjectsController",
    templateUrl: "app/pages/projects/projects.view.html",
    resolve: ["app/pages/projects/projects.style.css"],
  },
  {
    name: "setting",
    path: "/setting",
    controller: "SettingController",
    templateUrl: "app/pages/setting/setting.view.html",
    resolve: ["app/pages/setting/setting.style.css"],
  },
  {
    name: "team",
    path: "/team",
    controller: "TeamController",
    templateUrl: "app/pages/team/team.view.html",
    resolve: ["app/pages/team/team.style.css"],
  },
];
